# общий масштаб картинки
SCENE_SCALE = 1.0

# размеры труб
PIPE_THICK_WIDTH = 20 * SCENE_SCALE
PIPE_THIN_WIDTH = 10 * SCENE_SCALE

# размеры помпы
PUMP_HALF_WIDTH = 40 * SCENE_SCALE
PUMP_HALF_HEIGHT = 25 * SCENE_SCALE
PUMP_LINE_WIDTH = 4 * SCENE_SCALE
PUMP_THIN_LINE_WIDTH = 2 * SCENE_SCALE
IMPELLER_RADIUS = PUMP_HALF_HEIGHT / 1.6 * SCENE_SCALE

# размеры клапанов
VALVE_HALF_WIDTH = 15 * SCENE_SCALE
VALVE_HALF_HEIGHT = 20 * SCENE_SCALE
VALVE_LINE_WIDTH = 4 * SCENE_SCALE

#размеры бака
TANK_HALF_WIDTH = 90 * SCENE_SCALE
TANK_HALF_HEIGHT = 160 * SCENE_SCALE
TANK_LINE_WIDTH = 4 * SCENE_SCALE
TANK_CORNER_HEIGHT = 15 * SCENE_SCALE

TANK_HEATER_WIDTH = 80 * SCENE_SCALE
TANK_HEATER_HEIGHT = 25 * SCENE_SCALE

TANK_LIQUID_LEVEL_WIDTH = 30 * SCENE_SCALE
TANK_LIQUID_LEVEL_HEIGHT = 180 * SCENE_SCALE

TANK_LAMP_SIZE = 16 * SCENE_SCALE

# настройка потока жидкости
STREAM_OFFSET = 3
STREAM_TIMER = 100

# цвета
ELEMENT_GRADIENT_LIGHT = "#ECEFF1"
ELEMENT_GRADIENT_DARK = "#B0BEC5"
ELEMENT_GRADIENT_DARKER = "#546E7A"
TANK_BORDER_COLOR = "#696969"
TANK_BACKGROUND_COLOR = "#90A4AE"

HEATER_ON_COLOR = "#D84315"
HEATER_OFF_COLOR = "dimgray"

LAMP_OK_COLOR = "#8BC34A"
LAMP_ALARM_COLOR = "#F44336"

LEVEL_INDICATOR_COLOR = "#FFC107"