import math


class Settings:
    TELEMETRY_FREQ = 0.5

    # настройки графиков
    GRAPH_STEPS = [1, 5, 10, 25]
    GRAPH_SCALES = [12 * step for step in GRAPH_STEPS]
    BUFFER_LEN = math.ceil(GRAPH_SCALES[-1] / TELEMETRY_FREQ)

    # общий масштаб картинки
    SCENE_SCALE = 1.0

    # толщина контура
    LINE_WIDTH = 4 * SCENE_SCALE

    # размеры труб
    PIPE_THICK_WIDTH = 20 * SCENE_SCALE
    PIPE_THIN_WIDTH = 10 * SCENE_SCALE

    # размеры помпы
    PUMP_WIDTH = 40 * SCENE_SCALE
    PUMP_HEIGHT = 24 * SCENE_SCALE
    PUMP_LINE_WIDTH = 4 * SCENE_SCALE
    PUMP_THIN_LINE_WIDTH = 2 * SCENE_SCALE
    IMPELLER_RADIUS = PUMP_HEIGHT * 0.7

    # размеры клапанов
    VALVE_WIDTH = 30 * SCENE_SCALE
    VALVE_HEIGHT = 40 * SCENE_SCALE

    # размеры фильтра
    FILTER_WIDTH = 200 * SCENE_SCALE
    FILTER_HEIGHT = 200 * SCENE_SCALE
    FILTER_LINE_WIDTH = 4 * SCENE_SCALE

    # размеры бака
    TANK_WIDTH = 90 * SCENE_SCALE # половина ширины
    TANK_HEIGHT = 160 * SCENE_SCALE # половина высоты

    TANK_HEATER_WIDTH = TANK_WIDTH * 0.8
    TANK_HEATER_HEIGHT = TANK_HEIGHT * 0.2

    TANK_LIQUID_LEVEL_WIDTH = TANK_WIDTH * 0.33
    TANK_LIQUID_LEVEL_HEIGHT = TANK_HEIGHT * 1.2

    TANK_LAMP_SIZE = 16 * SCENE_SCALE

    # стрелочка
    ARROW_WIDTH = 8 * SCENE_SCALE
    ARROW_LENGTH = 10 * SCENE_SCALE

    # лейблы
    CIRCLE_LABEL_RADIUS = 30 * SCENE_SCALE

    # кнопки
    SCENE_BUTTON_WIDTH = 60 * SCENE_SCALE
    SCENE_BUTTON_FONT_SIZE = 14 * SCENE_SCALE

    # показометры
    VALUE_BOX_WIDTH = 80 * SCENE_SCALE
    VALUE_BOX_HEIGHT = 60 * SCENE_SCALE

    # настройка потока жидкости
    STREAM_OFFSET = 3
    STREAM_TIMER = 100
    STREAM_DURATION = 600

    # цвета
    ELEMENT_GRADIENT_LIGHT = "#ECEFF1"
    ELEMENT_GRADIENT_DARK = "#B0BEC5"
    ELEMENT_GRADIENT_DARKER = "#546E7A"

    PIPE_OUTER_COLOR_INACTIVE = "#78909C"
    PIPE_INNER_COLOR_INACTIVE = "#ECEFF1"
    PIPE_OUTER_COLOR_ACTIVE = "#2E7D32"
    PIPE_INNER_COLOR_ACTIVE = "#B4E6CD"
    FLOW_COLOR = "#1565C0"

    FILTER_BACKGROUND_COLOR = "#CFD8DC"
    FILTER_BACKGROUND_COLOR_2 = "#A9A9A9"

    BORDER_COLOR = "#696969"
    BACKGROUND_COLOR = "#90A4AE"

    IMPELLER_BACKGROUND_COLOR = "lightgray"

    HEATER_ON_COLOR = "#D84315"
    HEATER_OFF_COLOR = "#696969"

    LAMP_OK_COLOR = "#8BC34A"
    LAMP_ALARM_COLOR = "#F44336"

    LEVEL_INDICATOR_COLOR = "#FFC107"

    ARROW_COLOR = "#D84315"

    TEXT_COLOR = "black"

    BUTTON_BACKGROUND_COLOR = "#B3E5FC"
    BUTTON_BACKGROUND_HOVER_COLOR = "#90A4AE"
    BUTTON_BACKGROUND_PRESSED_COLOR = "#78909C"
    BUTTON_DISABLED_BACKGROUND_COLOR = "#B0BEC5"
    BUTTON_DISABLED_TEXT_COLOR = "#78909C"

    VALUE_BOX_BORDER_COLOR = BORDER_COLOR
    VALUE_BOX_TITLE_FONT_SIZE = 12 * SCENE_SCALE
    VALUE_BOX_VALUE_FONT_SIZE = 14 * SCENE_SCALE
    VALUE_BOX_VALUE_BACKGROUND_COLOR = "white"
    VALUE_BOX_TITLE_BACKGROUND_COLOR = "#B0BEC5"

    GRAPH_BACKGROUND_COLOR = "#072136"
    GRAPH_GRID_COLOR = "grey"
    GRAPH_LINE_1_COLOR = "#81C784"
    GRAPH_LINE_2_COLOR = "#90CAF9"
    GRAPH_BOTTOM_LINE_COLOR = "white"
