from widgets.settings import Settings

LEFT = -300 * Settings.SCENE_SCALE
RIGHT = 280 * Settings.SCENE_SCALE
TOP = -350 * Settings.SCENE_SCALE
BOTTOM = 300 * Settings.SCENE_SCALE

HEIGHT = BOTTOM - TOP
WIDTH = RIGHT - LEFT

HIGHER_BOTTOM = BOTTOM - Settings.PUMP_HEIGHT * 0.5

# центральная труба

MIDDLE_PIPE_Y = BOTTOM - HEIGHT * 0.55
MIDDLE_VALVE_PIPE_X, MIDDLE_VALVE_PIPE_Y = LEFT + WIDTH * 0.4, BOTTOM - HEIGHT * 0.48

# система колен

THIN_KNEE_HEIGHT = HEIGHT * 0.9
THIN_KNEE_OFFSET = WIDTH * 0.25

RIGHT_KNEE_X, RIGHT_KNEE_Y = RIGHT - WIDTH * 0.15, BOTTOM - HEIGHT * 0.82
KNEE_END_X, KNEE_END_Y = RIGHT_KNEE_X, BOTTOM - HEIGHT * 0.75

LEFT_THIN_KNEE_X, LEFT_THIN_KNEE_Y = LEFT + THIN_KNEE_OFFSET, BOTTOM - THIN_KNEE_HEIGHT
LEFT_THIN_KNEE_LOWER_X, LEFT_THIN_KNEE_LOWER_Y = LEFT_THIN_KNEE_X, BOTTOM - HEIGHT * 0.6
RIGHT_THIN_KNEE_X, RIGHT_THIN_KNEE_Y = RIGHT - THIN_KNEE_OFFSET, BOTTOM - THIN_KNEE_HEIGHT
RIGHT_THIN_KNEE_LOWER_X, RIGHT_THIN_KNEE_LOWER_Y = RIGHT_THIN_KNEE_X, BOTTOM - HEIGHT * 0.62

# клапаны

VALVE_V1_X, VALVE_V1_Y = LEFT, BOTTOM - HEIGHT * 0.62
VALVE_V2_X, VALVE_V2_Y = LEFT + WIDTH * 0.1, MIDDLE_PIPE_Y
VALVE_V3_X, VALVE_V3_Y = MIDDLE_VALVE_PIPE_X, MIDDLE_VALVE_PIPE_Y
VALVE_V5_X, VALVE_V5_Y = RIGHT, BOTTOM - HEIGHT * 0.1
VALVE_V6_X, VALVE_V6_Y = KNEE_END_X, KNEE_END_Y

# помпа

PUMP_X, PUMP_Y = LEFT + WIDTH * 0.8, BOTTOM

# бак

TANK_X, TANK_Y = 240 * Settings.SCENE_SCALE, 25 * Settings.SCENE_SCALE

# аэрофильтер

FILTER_X, FILTER_Y = LEFT + WIDTH * 0.5, BOTTOM - HEIGHT * 0.9