from widgets.settings import Settings

CENTER_X, CENTER_Y = 0, 0
WIDTH, HEIGHT = Settings.SCENE_SIZE
START_X, START_Y = CENTER_X - WIDTH / 2, CENTER_Y - HEIGHT / 2

STAND_BORDER_WIDTH, STAND_BORDER_HEIGHT = WIDTH * 0.47, HEIGHT * 0.9
START_BORDER_Y = START_Y + HEIGHT - STAND_BORDER_HEIGHT

HEADER_WIDTH, HEADER_HEIGHT = STAND_BORDER_WIDTH, HEIGHT - STAND_BORDER_HEIGHT - 2

# счетчик частиц
COUNTER_START_X, COUNTER_START_Y = CENTER_X, START_Y + STAND_BORDER_HEIGHT * 0.55
COUNTER_X, COUNTER_Y = CENTER_X, START_Y + STAND_BORDER_HEIGHT * 0.67

# масляный стенд

START_OIL_X, START_OIL_Y = START_X, START_BORDER_Y
HEADER_OIL_X, HEADER_OIL_Y = START_OIL_X, START_Y
# контур толстых труб
OIL_LEFT_TOP_KNEE_X, OIL_LEFT_TOP_KNEE_Y = START_OIL_X + STAND_BORDER_WIDTH * 0.08, START_OIL_Y + STAND_BORDER_HEIGHT * 0.15
OIL_RIGHT_TOP_KNEE_X, OIL_RIGHT_TOP_KNEE_Y = START_OIL_X + STAND_BORDER_WIDTH * 0.95, OIL_LEFT_TOP_KNEE_Y
OIL_LEFT_BOTTOM_KNEE_X, OIL_LEFT_BOTTOM_KNEE_Y = OIL_LEFT_TOP_KNEE_X, START_OIL_Y + STAND_BORDER_HEIGHT * 0.9
OIL_RIGHT_BOTTOM_KNEE_X, OIL_RIGHT_BOTTOM_KNEE_Y = OIL_RIGHT_TOP_KNEE_X, OIL_LEFT_BOTTOM_KNEE_Y + Settings.PUMP_HEIGHT * 0.5

# тонкие трубы верх
OIL_AFTER_FILTER_TOP_X, OIL_AFTER_FILTER_TOP_Y = START_OIL_X + STAND_BORDER_WIDTH * 0.32, OIL_LEFT_TOP_KNEE_Y
OIL_AFTER_FILTER_BOTTOM_X, OIL_AFTER_FILTER_BOTTOM_Y = OIL_AFTER_FILTER_TOP_X, COUNTER_START_Y
OIL_BEFORE_FILTER_TOP_X, OIL_BEFORE_FILTER_TOP_Y = START_OIL_X + STAND_BORDER_WIDTH * 0.72, OIL_LEFT_TOP_KNEE_Y
OIL_BEFORE_FILTER_BOTTOM_X, OIL_BEFORE_FILTER_BOTTOM_Y = OIL_BEFORE_FILTER_TOP_X, COUNTER_START_Y

# тонкие трубы бок
OIL_TANK_1_START_X, OIL_TANK_1_START_Y = OIL_LEFT_TOP_KNEE_X, START_OIL_Y + STAND_BORDER_HEIGHT * 0.5
OIL_TANK_1_END_X, OIL_TANK_1_END_Y = OIL_LEFT_TOP_KNEE_X + STAND_BORDER_WIDTH * 0.3, OIL_TANK_1_START_Y
OIL_TANK_2_END_X, OIL_TANK_2_END_Y = OIL_TANK_1_END_X, START_OIL_Y + STAND_BORDER_HEIGHT * 0.72
OIL_TANK_3_END_X, OIL_TANK_3_END_Y = OIL_TANK_1_END_X, START_OIL_Y + STAND_BORDER_HEIGHT * 0.55
OIL_TANK_4_END_X, OIL_TANK_4_END_Y = OIL_LEFT_TOP_KNEE_X + STAND_BORDER_WIDTH * 0.45, OIL_TANK_2_END_Y + Settings.PUMP_HEIGHT * Settings.SMALL_PUMP_QUOTIENT * 0.5
OIL_TANK_5_END_X, OIL_TANK_5_END_Y = OIL_TANK_4_END_X, OIL_LEFT_BOTTOM_KNEE_Y

# фильтры
OIL_FILTER_X, OIL_FILTER_Y = START_OIL_X + STAND_BORDER_WIDTH * 0.52, OIL_LEFT_TOP_KNEE_Y
OIL_FILTER_SMALL_X, OIL_FILTER_SMALL_Y = OIL_LEFT_TOP_KNEE_X, START_OIL_Y + STAND_BORDER_HEIGHT * 0.65

# помпа
OIL_PUMP_X, OIL_PUMP_Y = START_OIL_X + STAND_BORDER_WIDTH * 0.75, OIL_RIGHT_BOTTOM_KNEE_Y
OIL_SMALL_PUMP_X, OIL_SMALL_PUMP_Y = (OIL_TANK_2_END_X + OIL_TANK_4_END_X) * 0.5, OIL_TANK_4_END_Y

# бак
OIL_TANK_X, OIL_TANK_Y = START_OIL_X + STAND_BORDER_WIDTH * 0.18, OIL_LEFT_TOP_KNEE_Y + (OIL_LEFT_BOTTOM_KNEE_Y - OIL_LEFT_TOP_KNEE_Y) * 0.92
OIL_SMALL_TANK_X, OIL_SMALL_TANK_Y = OIL_TANK_2_END_X, OIL_TANK_1_END_Y + (OIL_TANK_4_END_Y - OIL_TANK_1_END_Y) * 0.45

# клапаны
OIL_VALVE_V2_X, OIL_VALVE_V2_Y = OIL_AFTER_FILTER_TOP_X, OIL_AFTER_FILTER_TOP_Y + (OIL_AFTER_FILTER_BOTTOM_Y - OIL_AFTER_FILTER_TOP_Y) * 0.2
OIL_VALVE_V3_X, OIL_VALVE_V3_Y = OIL_BEFORE_FILTER_TOP_X, OIL_BEFORE_FILTER_TOP_Y + (OIL_BEFORE_FILTER_BOTTOM_Y - OIL_BEFORE_FILTER_TOP_Y) * 0.2
OIL_VALVE_V5_X, OIL_VALVE_V5_Y = OIL_TANK_1_START_X + (OIL_TANK_1_END_X - OIL_TANK_1_START_X) * 0.2, OIL_TANK_1_START_Y
OIL_VALVE_V6_X, OIL_VALVE_V6_Y = OIL_TANK_4_END_X, OIL_TANK_4_END_Y + (OIL_TANK_5_END_Y - OIL_TANK_4_END_Y) * 0.2

# ротаметр
OIL_ROTAMETER_X, OIL_ROTAMETER_Y = OIL_TANK_4_END_X, OIL_TANK_4_END_Y + (OIL_TANK_5_END_Y - OIL_TANK_4_END_Y) * 0.65

# показометры
OIL_PRESSURE_BEFORE_X, OIL_PRESSURE_BEFORE_Y = START_OIL_X + STAND_BORDER_WIDTH * 0.75, START_OIL_Y + STAND_BORDER_HEIGHT * 0.1
OIL_PRESSURE_AFTER_X, OIL_PRESSURE_AFTER_Y = START_OIL_X + STAND_BORDER_WIDTH * 0.18, OIL_PRESSURE_BEFORE_Y
OIL_TEMPERATURE_BEFORE_X, OIL_TEMPERATURE_BEFORE_Y = START_OIL_X + STAND_BORDER_WIDTH * 0.88, START_OIL_Y + STAND_BORDER_HEIGHT * 0.18
OIL_MOISTURE_BEFORE_X, OIL_MOISTURE_BEFORE_Y = OIL_TEMPERATURE_BEFORE_X, OIL_TEMPERATURE_BEFORE_Y + Settings.VALUE_BOX_HEIGHT
OIL_TEMPERATURE_AFTER_X, OIL_TEMPERATURE_AFTER_Y = START_OIL_X + STAND_BORDER_WIDTH * 0.03, OIL_TEMPERATURE_BEFORE_Y
OIL_MOISTURE_AFTER_X, OIL_MOISTURE_AFTER_Y = OIL_TEMPERATURE_AFTER_X, OIL_TEMPERATURE_BEFORE_Y + Settings.VALUE_BOX_HEIGHT
OIL_TANK_TEMPERATURE_X, OIL_TANK_TEMPERATURE_Y = OIL_TANK_X - Settings.TANK_HEIGHT * 0.87, OIL_TANK_Y - Settings.TANK_WIDTH * 0.93
OIL_PUMP_FREQ_X, OIL_PUMP_FREQ_Y = OIL_PUMP_X - Settings.VALUE_BOX_WIDTH * 0.5, OIL_PUMP_Y - Settings.PUMP_HEIGHT * 4
OIL_FLOW_X, OIL_FLOW_Y = OIL_TEMPERATURE_BEFORE_X, START_OIL_Y + STAND_BORDER_HEIGHT * 0.65

# топливный стенд

START_FUEL_X, START_FUEL_Y = START_X + WIDTH - STAND_BORDER_WIDTH, START_BORDER_Y
HEADER_FUEL_X, HEADER_FUEL_Y = START_FUEL_X, START_Y

# контур толстых труб
FUEL_LEFT_TOP_KNEE_X, FUEL_LEFT_TOP_KNEE_Y = START_FUEL_X + STAND_BORDER_WIDTH * 0.08, START_FUEL_Y + STAND_BORDER_HEIGHT * 0.15
FUEL_RIGHT_TOP_KNEE_X, FUEL_RIGHT_TOP_KNEE_Y = START_FUEL_X + STAND_BORDER_WIDTH * 0.95, FUEL_LEFT_TOP_KNEE_Y
FUEL_LEFT_BOTTOM_KNEE_X, FUEL_LEFT_BOTTOM_KNEE_Y = FUEL_LEFT_TOP_KNEE_X, START_FUEL_Y + STAND_BORDER_HEIGHT * 0.9
FUEL_RIGHT_BOTTOM_KNEE_X, FUEL_RIGHT_BOTTOM_KNEE_Y = FUEL_RIGHT_TOP_KNEE_X, FUEL_LEFT_BOTTOM_KNEE_Y + Settings.PUMP_HEIGHT * 0.5

# тонкие трубы верх
FUEL_AFTER_FILTER_TOP_X, FUEL_AFTER_FILTER_TOP_Y = START_FUEL_X + STAND_BORDER_WIDTH * 0.32, FUEL_LEFT_TOP_KNEE_Y
FUEL_AFTER_FILTER_BOTTOM_X, FUEL_AFTER_FILTER_BOTTOM_Y = FUEL_AFTER_FILTER_TOP_X, COUNTER_START_Y
FUEL_BEFORE_FILTER_TOP_X, FUEL_BEFORE_FILTER_TOP_Y = START_FUEL_X + STAND_BORDER_WIDTH * 0.72, FUEL_LEFT_TOP_KNEE_Y
FUEL_BEFORE_FILTER_BOTTOM_X, FUEL_BEFORE_FILTER_BOTTOM_Y = FUEL_BEFORE_FILTER_TOP_X, COUNTER_START_Y

# тонкие трубы бок
FUEL_TANK_1_START_X, FUEL_TANK_1_START_Y = FUEL_LEFT_TOP_KNEE_X, START_FUEL_Y + STAND_BORDER_HEIGHT * 0.5
FUEL_TANK_1_END_X, FUEL_TANK_1_END_Y = FUEL_LEFT_TOP_KNEE_X + STAND_BORDER_WIDTH * 0.3, FUEL_TANK_1_START_Y
FUEL_TANK_2_END_X, FUEL_TANK_2_END_Y = FUEL_TANK_1_END_X, START_FUEL_Y + STAND_BORDER_HEIGHT * 0.72
FUEL_TANK_3_END_X, FUEL_TANK_3_END_Y = FUEL_TANK_1_END_X, START_FUEL_Y + STAND_BORDER_HEIGHT * 0.55
FUEL_TANK_4_END_X, FUEL_TANK_4_END_Y = FUEL_LEFT_TOP_KNEE_X + STAND_BORDER_WIDTH * 0.45, FUEL_TANK_2_END_Y + Settings.PUMP_HEIGHT * Settings.SMALL_PUMP_QUOTIENT * 0.5
FUEL_TANK_5_END_X, FUEL_TANK_5_END_Y = FUEL_TANK_4_END_X, FUEL_LEFT_BOTTOM_KNEE_Y

# фильтры
FUEL_FILTER_X, FUEL_FILTER_Y = START_FUEL_X + STAND_BORDER_WIDTH * 0.52, FUEL_LEFT_TOP_KNEE_Y
FUEL_FILTER_SMALL_X, FUEL_FILTER_SMALL_Y = FUEL_LEFT_TOP_KNEE_X, START_FUEL_Y + STAND_BORDER_HEIGHT * 0.65

# помпа
FUEL_PUMP_X, FUEL_PUMP_Y = START_FUEL_X + STAND_BORDER_WIDTH * 0.75, FUEL_RIGHT_BOTTOM_KNEE_Y
FUEL_SMALL_PUMP_X, FUEL_SMALL_PUMP_Y = (FUEL_TANK_2_END_X + FUEL_TANK_4_END_X) * 0.5, FUEL_TANK_4_END_Y

# бак
FUEL_TANK_X, FUEL_TANK_Y = START_FUEL_X + STAND_BORDER_WIDTH * 0.18, FUEL_LEFT_TOP_KNEE_Y + (FUEL_LEFT_BOTTOM_KNEE_Y - FUEL_LEFT_TOP_KNEE_Y) * 0.92
FUEL_SMALL_TANK_X, FUEL_SMALL_TANK_Y = FUEL_TANK_2_END_X, FUEL_TANK_1_END_Y + (FUEL_TANK_4_END_Y - FUEL_TANK_1_END_Y) * 0.45

# клапаны
FUEL_VALVE_V2_X, FUEL_VALVE_V2_Y = FUEL_BEFORE_FILTER_TOP_X, FUEL_BEFORE_FILTER_TOP_Y + (FUEL_BEFORE_FILTER_BOTTOM_Y - FUEL_BEFORE_FILTER_TOP_Y) * 0.2
FUEL_VALVE_V3_X, FUEL_VALVE_V3_Y = FUEL_AFTER_FILTER_TOP_X, FUEL_AFTER_FILTER_TOP_Y + (FUEL_AFTER_FILTER_BOTTOM_Y - FUEL_AFTER_FILTER_TOP_Y) * 0.2
FUEL_VALVE_V5_X, FUEL_VALVE_V5_Y = FUEL_TANK_1_START_X + (FUEL_TANK_1_END_X - FUEL_TANK_1_START_X) * 0.2, FUEL_TANK_1_START_Y
FUEL_VALVE_V6_X, FUEL_VALVE_V6_Y = FUEL_TANK_4_END_X, FUEL_TANK_4_END_Y + (FUEL_TANK_5_END_Y - FUEL_TANK_4_END_Y) * 0.2

# ротаметр
FUEL_ROTAMETER_X, FUEL_ROTAMETER_Y = FUEL_TANK_4_END_X, FUEL_TANK_4_END_Y + (FUEL_TANK_5_END_Y - FUEL_TANK_4_END_Y) * 0.65

# показометры
FUEL_PRESSURE_BEFORE_X, FUEL_PRESSURE_BEFORE_Y = START_FUEL_X + STAND_BORDER_WIDTH * 0.75, START_FUEL_Y + STAND_BORDER_HEIGHT * 0.1
FUEL_PRESSURE_AFTER_X, FUEL_PRESSURE_AFTER_Y = START_FUEL_X + STAND_BORDER_WIDTH * 0.18, FUEL_PRESSURE_BEFORE_Y
FUEL_TEMPERATURE_BEFORE_X, FUEL_TEMPERATURE_BEFORE_Y = START_FUEL_X + STAND_BORDER_WIDTH * 0.88, START_FUEL_Y + STAND_BORDER_HEIGHT * 0.18
FUEL_MOISTURE_BEFORE_X, FUEL_MOISTURE_BEFORE_Y = FUEL_TEMPERATURE_BEFORE_X, FUEL_TEMPERATURE_BEFORE_Y + Settings.VALUE_BOX_HEIGHT
FUEL_TEMPERATURE_AFTER_X, FUEL_TEMPERATURE_AFTER_Y = START_FUEL_X + STAND_BORDER_WIDTH * 0.03, FUEL_TEMPERATURE_BEFORE_Y
FUEL_MOISTURE_AFTER_X, FUEL_MOISTURE_AFTER_Y = FUEL_TEMPERATURE_AFTER_X, FUEL_TEMPERATURE_BEFORE_Y + Settings.VALUE_BOX_HEIGHT
FUEL_TANK_TEMPERATURE_X, FUEL_TANK_TEMPERATURE_Y = FUEL_TANK_X - Settings.TANK_HEIGHT * 0.87, FUEL_TANK_Y - Settings.TANK_WIDTH * 0.93
FUEL_PUMP_FREQ_X, FUEL_PUMP_FREQ_Y = FUEL_PUMP_X - Settings.VALUE_BOX_WIDTH * 0.5, FUEL_PUMP_Y - Settings.PUMP_HEIGHT * 4
FUEL_FLOW_X, FUEL_FLOW_Y = FUEL_TEMPERATURE_BEFORE_X, START_FUEL_Y + STAND_BORDER_HEIGHT * 0.65
