from widgets.settings import Settings

CENTER_X, CENTER_Y = 0, 0
WIDTH, HEIGHT = Settings.SCENE_SIZE
START_X, START_Y = CENTER_X - WIDTH / 2, CENTER_Y - HEIGHT / 2

STAND_BORDER_WIDTH, STAND_BORDER_HEIGHT = WIDTH * 0.45, HEIGHT * 0.9
START_BORDER_Y = START_Y + HEIGHT - STAND_BORDER_HEIGHT
START_OIL_X, START_OIL_Y = START_X, START_BORDER_Y
START_FUEL_X, START_FUEL_Y = START_X + WIDTH - STAND_BORDER_WIDTH, START_BORDER_Y

HEADER_OIL_X, HEADER_OIL_Y = START_OIL_X, START_Y
HEADER_FUEL_X, HEADER_FUEL_Y = START_FUEL_X, START_Y
HEADER_WIDTH, HEADER_HEIGHT = STAND_BORDER_WIDTH, HEIGHT - STAND_BORDER_HEIGHT - 2